site_name: Wyvern Bot
repo_url: https://github.com/WyvernGroup/bot-docs
repo_name: WyvernGroup/bot-docs
theme:
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"


      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/H2g5638vyD

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Overview:
      - Home: index.md
      - Navigation: navigation.md
      - Commands: commands.md
      - Changelog: changelog.md
  - Legal:
      - Privacy Policy: legal/privacy.md
      - Terms of Service: legal/tos.md
copyright: Copyright &copy; 2021 - 2022 Wyvern Bot
