name: ci 
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force
  cname:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure CNAME
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout gh-pages    
          echo docs.wyvernbot.xyz > CNAME
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "configure CNAME"  
          git push origin gh-pages
